import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import AuthProvider from '@/providers/auth'
import QueryProvider from '@/providers/query-provider'
import { TokenWatcher } from '@/auth/token-watcher'

const mulish = Mulish({
  subsets: ['latin-ext'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className} dark antialiased`}>
        <AuthProvider>
          <div className="flex flex-col lg:h-full lg:overflow-hidden">
            <QueryProvider>{children}</QueryProvider>
            <TokenWatcher />

            <Toaster />
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
